### ISSUE TITLE
Code of Coduct and Contribution Guidelines

### ISSUE THREAD

**Issue by vektorious** [FOSH-following-demand/Flow-Through-Colorimeter#6]
The Code of Conduct and the Contribution Guidelines (contributing.md) are important parts of an open project.

[Here is a bit more about how to add a Code of Conduct](https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project) and here [for the contribution guidelines](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors). If you need some inspiration check out other projects or e.g. [this example](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

**Comment by pcremades** [comment]
Another [example](http://openhardware.science/gosh-2017/gosh-code-of-conduct/)

**Comment by dsdrajlin** [comment]
The [Contributor Covenant Code of Conduct](https://github.com/FOSH-following-demand/Flow-Through-Colorimeter/blob/master/CODE_OF_CONDUCT.md) is proposed for this project.

**Comment by pcremades** [comment]
Done
